services:
  - type: web
    plan: free
    name: Gangster-Baby-Renamer-V2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https:https://github.com/Sathask/Gangster-Baby-Renamer-V2/tree/main.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: LAZY_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        sync: false
      - key: BOT_USERNAME
        sync: false
